### PR TITLE
Bump 1.3.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by psainics**
Bump the snapshot version to 1.3.1-SNAPSHOT for next SNAPSHOT version !

### CODE REVIEW

**Review by itsankit-google — COMMENTED** [review]
It should be snapshot removal not bump, it was already snapshot, was `1.3.0` already released before?

**Comment by psainics** [comment]
https://github.com/data-integrations/ariba-plugins/tree/release/1.3.0

**Review by itsankit-google — COMMENTED** [review]
This is incorrect release branch names don't contain patch version, please create new `release/1.3` branch from this branch.

**Comment by itsankit-google** [comment]
Also I don't see the plugin in `hub`, where was it released?
https://github.com/cdapio/sap-hub/tree/deploy/packages/plugin-ariba

**Comment by psainics** [comment]
I don't have access to the hub, from the commit i thought this was released!

**Comment by psainics** [comment]
This bump is not required we can close this PR,
A new PR (https://github.com/data-integrations/ariba-plugins/pull/33) has been raised with correct base !

**Pull request closed without merging**
